name: Crawl and validate

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run validation script
      run: |
        chmod +x crawl-script.sh
        ./crawl-script.sh
